# Generated by Django 5.2.4 on 2025-08-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do livro', max_length=200)),
                ('autor', models.CharField(help_text='Autor do livro', max_length=150)),
                ('genero', models.CharField(help_text='Gênero', max_length=100)),
                ('ano_publicacao', models.IntegerField(help_text='Ano de Publicação')),
                ('isbn', models.CharField(help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1, help_text='Quantidade em estoque')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
