# Generated by Django 5.2.5 on 2025-08-06 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField(help_text='Data prevista para devolução')),
                ('data_devolucao_real', models.DateField(blank=True, help_text='Data em que o livro foi devolvido', null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido')], default='ativo', max_length=10)),
                ('aluno', models.ForeignKey(help_text='Aluno que realizou o empréstimo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(help_text='Livro a ser emprestado', on_delete=django.db.models.deletion.PROTECT, to='biblioteca_core.livro')),
            ],
            options={
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
