# Generated by Django 5.2.5 on 2025-08-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_core', '0002_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, help_text='Capa do livro', null=True, upload_to='capas/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, help_text='Breve resumo do livro', null=True),
        ),
    ]
